defaultBaseImage: docker.io/alpine:3.18.4

builds:
- id: main
  dir: .
  main: ./cmd/collector
  flags:
  - -tags
  - netgo,timetzdata
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.version={{.Env.VERSION}}
